### ISSUE TITLE
How to pass a value prompt answer using the REST API?

### ISSUE THREAD

**Issue by zjazj** [MicroStrategy/rest-api-samples#4]

**Comment by Dholmblad** [comment]
Hi @zjazj 

Take a look in the MSDL at the documentation which shows examples for answering value prompts. We will be publishing more samples soon which show this as well. 

https://lw.microstrategy.com/msdz/MSDL/GARelease_Current/docs/projects/RESTSDK/Content/topics/REST_API/REST_API_Prompts_ValuePrompts.htm#Answering_a_value_prompt


PUT /documents/{id}/instances/{instanceId}/prompts/answers

Numeric
`{

  "prompts":[

    {

      "key":"9BC4631D436CAA78D7A70AB2D0635D88@0@10",

      "type":"VALUE",

      "answers": "2015"

    }

  ]

}`

Date

`{

  "prompts":[

    {

      "key":"A46842D548C3F0CEEDD3979528480FE5@0@10",

      "type":"VALUE",

      "answers": "2017-09-27T23:37:39.000+0000"

    }

  ]

}`

Text

`{

  "prompts":[

    {

      "key":"CF604AA948AF21CBC67AF98FBA614E0F@0@10",

      "type":"VALUE",

      "answers": "q"

    }

  ]

}`

BigDecimal

`{

  "prompts":[

    {

      "key":"6F96306444CD3F2597B3FF92E2220356@0@10",

      "type":"VALUE",

      "answers": "123"

    }

  ]

}

`
